# -*- coding: utf-8 -*-
"""Generate G_glossary.tex with proper UTF-8 encoding."""
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "chapters" / "G_glossary.tex"

# (English term, Chinese term label, Chinese definition)
ENTRIES = [
    ("active edge", "有效边沿",
     "使数据锁存到触发器的时钟信号由低到高或由高到低的转换。"),
    ("aggressor net", "aggressor 网",
     "因与另一网（受害网，victim net）之间的寄生交叉电容，对受害网造成不良串扰效应的网。"),
    ("annotation", "标注",
     "附着于对象的信息（如附在网上的延时值）；或将信息附着到对象的过程。"),
    ("AOCV", "AOCV（高级片上变异）",
     "Advanced on-chip variation（AOCV）是 Synopsys 技术，根据所分析路径的位置与逻辑深度减少不必要的悲观性。"),
    ("arc", "弧",
     "与特定路径相关的一组时序约束。"),
    ("ASIC", "ASIC",
     "Application-specific integrated circuit；为执行特定任务而制造的专用集成电路。"),
    ("ASIC vendor", "ASIC 厂商",
     "为他人制造集成电路的公司，使用具有定义功能与时序特性的标准电路元件。"),
    ("asynchronous", "异步",
     "两个不同时钟或信号之间无时序关系（转换可相对于彼此在任意时刻发生）。"),
    ("attribute", "属性",
     r"与对象关联的字符串或值，携带该对象的信息。例如附在单元上的 \texttt{number\_of\_pins} 属性表示单元引脚数。可用 \cmd{get\_attribute} 查询属性值。"),
    ("back-annotation", "反标",
     "将详细寄生数据应用到设计的过程，以便更准确分析最终电路时序。数据来自布局完成后的外部工具。"),
    ("baseline image", "基线映像",
     "在 DMSA 分析中，由网表映像与场景的公共数据文件合并产生的映像。"),
    ("borrowing", "借用",
     "一种分析技术：当下一级为透明模式工作的电平敏感锁存器时，允许路径的一部分从设计的下一级借用时序裕量。"),
    ("capture", "捕获",
     "在路径端点用时钟将数据锁存到锁存器或触发器的过程，从而获取由路径起点较早时钟边沿发射的数据。"),
    ("cell", "单元",
     "集成电路中具有已知功能与时序特性的组件，可作为构建更大电路的元素。"),
    ("cell delay", "单元延时",
     "路径中从单元（逻辑门）输入到输出的延时。"),
    ("clock", "时钟",
     r"将数据锁存到时序元件的周期信号。用 \cmd{create\_clock} 或 \cmd{create\_generated\_clock} 定义信号为时钟并指定其时序特性。"),
    ("clock path", "时钟路径",
     "从时钟输入端口或内部单元引脚开始、到时序元件时钟输入引脚结束的时序路径。"),
    ("clock gating", "时钟门控",
     "用时钟信号上的组合逻辑元件（如多路选择器或 AND 门）控制时钟，以在选定时刻关断时钟或修改时钟脉冲特性。"),
    ("clock latency", "时钟延迟",
     "见 latency（延迟）。"),
    ("clock reconvergence pessimism", "时钟重汇聚悲观性",
     "静态时序分析的不准确性：两条不同时钟路径部分共享同一段物理路径，分析工具对一条路径用共享段最小延时、对另一条用最大延时。纠正该不准确称为时钟重汇聚悲观性消除（CRPR）。"),
    ("clock skew", "时钟偏斜",
     "见 skew（偏斜）。"),
    ("closing edge", "关闭边沿",
     "将数据锁存到电平敏感锁存器、结束透明模式并使数据输入不敏感的时钟边沿。"),
    ("collection", "集合",
     r"从已加载设计中选取的对象集。例如 \texttt{set mylist [get\_clocks \"CLK*\"]} 创建时钟集合并将变量 \texttt{mylist} 设为该集合，随后可对集合使用如 \cmd{remove\_clock \$mylist} 的命令。"),
    ("combinational feedback loop", "组合反馈环",
     "信号路径回到起点的组合逻辑网络。PrimeTime 必须在环内某点断开环（停止追踪信号）。"),
    ("combinational logic", "组合逻辑",
     "仅含无记忆或内部状态元件的逻辑网络。可含 AND、OR、XOR、反相器，但不能含触发器、锁存器、寄存器或 RAM。"),
    ("command focus", "命令焦点",
     "在 DMSA 分析中，分析命令所应用的当前场景集。命令焦点可包含会话中全部场景或仅子集。"),
    ("common point", "公共点",
     "存在时钟重汇聚悲观性的路径中，发射与捕获时钟路径共享段上最后一个单元输出。"),
    ("conditional timing arc", "条件时序弧",
     "延时值取决于某些条件（如输入逻辑状态）的时序弧。"),
    ("conservative", "保守",
     "倾向于悲观（而非乐观）以确保检测到所有违例的分析算法或技术。"),
    ("constraint", "约束",
     "应用于路径或设计的时序规格或要求。时序约束限制信号到达器件输入或于器件输出有效的允许时间范围。"),
    ("context characterization", "上下文表征",
     r"使用 \cmd{characterize\_context} 捕获子设计在芯片级时序环境中时序上下文的过程，允许在 PrimeTime 中独立分析子设计或在 Design Compiler 中优化。实例的时序上下文包括时钟信息、输入到达时间、输出延时、时序例外、设计规则、传播常量、线负载模型、输入驱动与电容负载。"),
    ("context independent", "上下文无关",
     r"在不同上下文中均准确。该术语指时序模型的可用性而非行为。例如 \cmd{extract\_model} 创建的模型是上下文无关的，即可在不同上下文中准确使用（其行为随使用上下文变化）。"),
    ("CPU time", "CPU 时间",
     "计算机中央处理器完成任务所用时间（由工具报告）。衡量任务所需计算资源；CPU 时间小于实际经过时间。"),
    ("critical path", "关键路径",
     "路径组中违例最大（或时序 slack 最小）的路径。"),
    ("critical region", "关键区域",
     "在 HyperTrace 加速 PBA 中，设计中 slack 关键（违例）的引脚集合。slack 临界阈值通常为 0，但可配置。"),
    ("crosstalk", "串扰",
     "网与物理相邻网之间寄生电容引起的不良效应。相邻网上的信号转换可在受影响网上引起噪声凸起或转换时间变化。"),
    ("current design", "当前设计",
     r"当前视为设计层次顶层的设计。可用 \cmd{current\_design} 指定。"),
    ("current image", "当前映像",
     "在 DMSA 分析中，当场景数多于主机数、工作进程需切换至另一场景时自动保存到磁盘的映像。"),
    ("current instance", "当前实例",
     r"设计层次中实例专用命令默认操作的实例（层次单元）。可用 \cmd{current\_instance} 设置，类似 Linux 中的 \texttt{cd}。"),
    ("current session", "当前会话",
     "在 DMSA 分析中，当前选定进行分析的场景集。"),
    ("data check", "数据检查",
     "两个数据信号之间的时序检查，如握手接口信号或 preset/clear 引脚间的 recovery/removal 检查。被检查的两信号称为 constrained 与 related 信号；related 信号在时序关系中被视为时钟。例如 setup 数据检查验证 constrained 信号在 related 信号有效边沿之前稳定。"),
    ("data path", "数据路径",
     r"从数据发射点到数据捕获点的时序路径。``路径''通常指数据路径，另有时钟路径、\texttt{async\_default} 路径等。"),
    ("database (.db) format", "数据库（.db）格式",
     r"Synopsys 用于存储设计、.lib 逻辑库、时钟信息、反标寄生信息与时序模型的文件格式。可用 \cmd{read\_db} 将部分或全部信息读入 PrimeTime。Design Compiler 与 Formality 等工具也使用 .db 文件。"),
    ("Design Compiler", "Design Compiler",
     "Synopsys 工具，可将硬件描述语言定义的设计综合为优化的、工艺相关的门级设计。支持多种 flat 与层次风格，可针对速度、面积与功耗优化组合与时序设计。与 PrimeTime 配合良好，但是可独立使用的工具。"),
    ("edge-sensitive latch", "边沿敏感锁存器",
     "触发器；在时钟输入每个有效边沿捕获数据的寄存器元件。有效边沿可为低到高或高到低，取决于器件类型。"),
    ("endpoint", "端点",
     "时序路径在设计中结束的位置，即数据被时钟边沿捕获或必须在特定时刻可用的位置。每个端点必须是寄存器数据输入引脚或输出端口。"),
    ("exception", "例外",
     "见 timing exception（时序例外）。"),
    ("exclusive clocks", "互斥时钟",
     "永不同时活动的两个时钟（例如因多路复用）。"),
    ("extracted timing model", "提取时序模型",
     r"由 \cmd{extract\_model} 从门级网表创建的时序模型，表示块的时序特性（弧值），但不含功能信息，无法综合。"),
    ("false path", "伪路径",
     r"设计中存在但不应做时序分析的路径，例如两个永不同时使能的多路复用块之间的路径。须在 PrimeTime 中用 \cmd{set\_false\_path} 定义为时序例外，或用 \cmd{set\_disable\_timing} 将相关对象排除在分析之外。"),
    ("fanin", "扇入",
     "影响指定时序端点（sink）的端口与引脚集合。若存在经组合逻辑从引脚到该 sink 的时序路径，则该引脚在时序扇入中。扇入追踪在寄存器（时序单元）时钟引脚处停止。"),
    ("fanout", "扇出",
     "在 PrimeTime 中通常指时序扇出（transitive fanout），即受指定源端口或引脚影响的时序端点上的端口与引脚集合。若存在经组合逻辑从源到引脚的时序路径，则该引脚在时序扇出中。扇出追踪在寄存器输入处停止。注意时序扇出不同于直接扇出（direct fanout，即连接到单元输出的单元输入数量）。"),
    ("flip-flop", "触发器",
     "由边沿敏感时钟输入控制的存储元件。通常有输入 D、输出 Q、时钟输入，可能还有异步 set/clear。时钟有效边沿时锁存 D 的值并在 Q 保持。有效边沿可为上升或下降，取决于触发器类型。"),
    ("gated clock", "门控时钟",
     "可被逻辑修改的时钟信号，例如为省电而可关断的时钟。"),
    ("generated clock", "生成时钟",
     r"由集成电路内部生成的时钟；非直接来自外部源。例如由系统时钟生成的二分频时钟。用 \cmd{create\_generated\_clock} 指定生成时钟特性。"),
    ("glitch", "毛刺",
     "足以导致逻辑失败的噪声凸起。"),
    ("graph-based refinement", "基于图的精化",
     "在 HyperTrace 加速 PBA 中，在关键区域内选择性信号合并以提高精度，同时保持基于图表示的运行时间与内存优势的过程。"),
    ("hold constraint", "保持约束",
     "规定数据在锁入器件的时钟边沿之后必须在器件输入保持稳定多长时间的时序约束。相对于时钟对时序路径施加最小延时。"),
    ("HyperGrid", "HyperGrid",
     "PrimeTime 功能，通过在多台主机上并行运行的工作进程分析超大设计。可用常规 PrimeTime 分析相同命令探索与报告整个设计。"),
    ("HyperScale", "HyperScale",
     "PrimeTime 层次化分析方法，用独立运行分析块级与顶层部分，并准确处理跨层次边界的时序接口。"),
    ("HyperTrace", "HyperTrace",
     "加速穷举基于路径分析（PBA）的 PrimeTime 技术。识别时序图关键区域，基于图的精化在关键区域内应用选择性信号合并以提高精度，再用该精化时序驱动穷举 PBA 搜索。"),
    ("I-V characteristics (steady-state)", "I-V 特性（稳态）",
     "单元输出的电流--电压特性；输出保持逻辑 1 或 0 时电流随电压的变化。PrimeTime SI 用此信息计算串扰噪声效应。"),
    ("island", "岛",
     "见 voltage area（电压区域）。"),
    ("inout pin", "inout 引脚",
     "单元的双向引脚；可作为输入或输出工作。"),
    ("input delay", "输入延时",
     "规定从时钟边沿到信号到达指定输入端口的最小或最大延时的约束。PrimeTime 用此信息检查输入端口及该输入扇出中的时序违例。"),
    ("intellectual property", "知识产权",
     "一家公司拥有并授权另一家公司使用的信息。例如一家公司可授权在另一家公司的 ASIC 中使用芯片子模块设计（如微处理器核），提供版图、电气规格与时序模型而不公开子模块网表。"),
    ("interface logic model (ILM)", "接口逻辑模型（ILM）",
     "已被 HyperScale 层次化分析取代的过时时序模型类型。"),
    ("latch", "锁存器",
     "由电平敏感门控输入控制的存储元件。门控有效时输出跟随输入；门控由有效变为无效时锁存输入值，输出保持该值。门控信号由无效到有效的边沿称为 opening edge（打开边沿），由有效到无效称为 closing edge（关闭边沿）。"),
    ("latency", "延迟",
     "时钟信号从时钟源传播到设计内特定点所需时间。时钟信号在此时间内``隐藏''（潜伏）。"),
    ("launch", "发射",
     "在路径起点用时钟将数据从锁存器或触发器时钟输出的过程，释放的数据由路径端点另一时钟边沿捕获。"),
    ("layout", "版图",
     "生成集成电路元件与互连的几何位置、尺寸与形状的过程。版图信息可供外部工具生成元件与互连寄生电阻电容的准确信息，随后在 PrimeTime 中反标以进行更准确的时序分析。"),
    ("leaf level", "叶级",
     "设计层次中包含最低级库单元（如树的叶子）的层次。"),
    ("level-sensitive latch", "电平敏感锁存器",
     "门控输入有效时允许数据从输入传到输出的寄存器；门控无效时保持数据输出恒定。"),
    ("logic library", "逻辑库",
     "含设计中电路元件功能与时序特性信息的数据库，以 Liberty 语法指定时也称 .lib 逻辑库。通常由 ASIC 厂商提供。"),
    ("Liberty", "Liberty",
     "指定单元库信息（如延时、时序约束与功耗）的标准格式。SiliconSmart 库表征工具生成 Liberty（.lib）文本文件；Library Compiler 读入 Liberty 并生成编译单元库（.db）文件。"),
    ("Library Compiler", "Library Compiler",
     "Synopsys 工具，为 PrimeTime、Design Compiler 等创建库数据库。从 Liberty（.lib）文本文件读入 ASIC 库描述并编译为 .db 格式数据库。"),
    ("LVF (Liberty Variation Format)", "LVF（Liberty 变异格式）",
     "Liberty 语法中指定单元变异参数（如单元延时均值与标准差 sigma）的标准格式。"),
    ("manager process", "管理进程",
     "在 DMSA 与 HyperGrid 分布式分析中，由用户调用、编排一个或多个工作进程的 PrimeTime 进程。"),
    ("multicycle path", "多周期路径",
     r"设计为数据从起点到终点传播需超过一个时钟周期的路径。例如乘法器（慢组合逻辑）可能设计为四个时钟周期后捕获有效结果。须用 \cmd{set\_multicycle\_path} 定义为时序例外。"),
    ("native", "原生",
     "完全在 PrimeTime 内工作、不需外部程序的命令或过程。"),
    ("net arc", "网弧",
     "从驱动引脚到同一网上负载引脚的时序弧，因寄生网电容具有非零延时。"),
    ("net delay", "网延时",
     "时序路径中从单元输出到下一单元输入的延时，由互连寄生电容引起。"),
    ("network latency", "网络延迟",
     "时钟信号从时钟定义点传播到寄存器时钟引脚的时间。"),
    ("nonlinear delay model (NLDM)", "非线性延时模型（NLDM）",
     "在 .lib 逻辑库中指定单元延时的标准表格式。"),
    ("noise", "噪声",
     "稳态网模拟电压的暂时偏离或变化，如 CMOS 门输出处的串扰感应电压凸起。"),
    ("noise bump", "噪声凸起",
     "绘制成电压对时间时呈隆起状（常建模为三角形）的噪声事件。"),
    ("noise immunity curve", "噪声免疫曲线",
     "规定单元输入允许的最大噪声凸起尺寸而不在输出产生传播噪声的函数，常近似为双曲线。"),
    ("noise margin", "噪声裕量",
     "DC 噪声裕量是某逻辑电平最极端输出电压（如 VOLmax）与同逻辑电平最极端输入阈值（如 VILmax）之差。AC 噪声裕量是单元输入允许而不在输出产生逻辑失败的最大噪声凸起（伏特）。"),
    ("noise slack", "噪声 slack",
     "输入出现噪声凸起时避免逻辑失败的量，等于失败阈值电压减凸起高度，再乘以凸起宽度。单位为库电压单位乘以库时间单位。"),
    ("no-change constraint", "不变约束",
     "数据信号在控制信号脉冲之前、期间与之后必须保持不变的时间。例如地址信号在写脉冲期间必须稳定：在控制脉冲前沿前稳定 setup 时间、脉冲期间、以及后沿后稳定 hold 时间。"),
    ("opening edge", "打开边沿",
     "断言电平敏感锁存器门控输入的时钟边沿。锁存器从打开边沿到关闭边沿处于透明状态。"),
    ("operating conditions", "工作条件",
     "电路工作的工艺、电压与温度条件，影响单元时序特性。"),
    ("optimistic", "乐观",
     "存在已知精度限制的分析算法或技术，不准确可能使电路看起来比实际有更多时序 slack，从而可能检测不到实际电路中的违例。"),
    ("output delay", "输出延时",
     "从输出端口到捕获该端口数据的外部时序器件的最小或最大延时约束，规定信号在输出端口必须可用的时间以满足外部时序元件的 setup 与 hold。"),
    ("parasitic capacitance", "寄生电容",
     "网与相邻互连或衬底物理邻近引起的网电容；或网中 p-n 结电荷存储效应。"),
    ("parasitic resistance", "寄生电阻",
     "互连或网因互连材料有限电导率产生的电阻。"),
    ("partition", "分区",
     "在 HyperGrid 分布式分析中，被拆分为多块以在多台机器上并行分析的大设计的一部分。"),
    ("path", "路径",
     "从寄存器时钟引脚或输入端口开始、经任意数量组合逻辑、在寄存器数据输入引脚或输出端口结束的点到点序列。时钟边沿在路径起点发射的数据经组合逻辑传播到端点，由另一时钟边沿捕获。"),
    ("path endpoint", "路径端点",
     "见 endpoint（端点）。"),
    ("path group", "路径组",
     r"相关路径的组，由 \cmd{create\_clock} 隐式分组或 \cmd{group\_path} 显式分组。默认情况下，由同一时钟定时的端点路径属于同一路径组。路径组影响 PrimeTime 中违例报告，也影响 Design Compiler 优化不同路径的相对力度。"),
    ("path inspector", "路径检查器",
     "PrimeTime GUI 中显示时序路径详细信息的窗口，如路径原理图、路径元素表、时序波形、路径延时剖面与文本报告。"),
    ("path startpoint", "路径起点",
     "见 startpoint（起点）。"),
    ("pessimistic", "悲观",
     "存在已知精度限制的分析算法或技术，不准确可能使电路看起来比实际有更少的时序 slack，从而可能报告实际电路中不存在的违例。"),
    ("pin", "引脚",
     "设计中单元实例的输入或输出。引脚时序约束在 .lib 逻辑库中指定。"),
    ("port", "端口",
     r"设计的输入或输出。用 \cmd{set\_input\_delay} 与 \cmd{set\_output\_delay} 为端口指定时序约束。"),
    ("postlayout", "后版图",
     "版图之后；可获得详细寄生数据用于设计反标的阶段。"),
    ("procedure (Tcl)", "过程（Tcl）",
     r"用户在 PrimeTime 中用 \cmd{proc} 创建的自定义命令。定义后可像标准命令一样运行，可带参数并使用局部与外部变量。"),
    ("propagated noise", "传播噪声",
     "由驱动该网的门输入噪声引起的网上的噪声凸起。例如输入为 0、输出为 1 的反相器，输入正凸起可在输出产生负凸起。"),
    (r"pt\_shell", r"pt\_shell",
     "PrimeTime 的基于文本命令行界面，可输入命令、运行脚本并以文本查看结果。与之相对，PrimeTime GUI 还提供菜单、对话框、按钮及分析结果的图形展示。"),
    ("quick timing model", "快速时序模型",
     r"当无网表且无其他时序模型时，用 PrimeTime 命令为块创建的临时时序模型。使用 \cmd{create\_qtm\_model} 创建、\cmd{create\_qtm\_port} 与 \cmd{create\_qtm\_delay\_arc} 指定特性、\cmd{save\_qtm\_model} 保存。"),
    ("RC", "RC",
     "电阻--电容，用单个电阻与电容表示网寄生的简单寄生模型。"),
    ("reconvergence pessimism", "重汇聚悲观性",
     "见 clock reconvergence pessimism（时钟重汇聚悲观性）。"),
    ("recovery constraint", "恢复约束",
     "异步控制信号（如触发器异步 clear 输入）变为无效与随后有效时钟边沿之间所需的最短时间。类似有效时钟边沿的 setup 检查。若有效时钟边沿在异步输入变为无效后过早发生，寄存器数据不确定，因为时钟输入数据可能无效。"),
    ("register", "寄存器",
     "触发器（边沿敏感时钟）或锁存器（电平敏感门控）的叶级实例。"),
    ("related signal", "相关信号",
     "在数据到数据时序检查中被视为时钟的数据信号。另一被检查信号称为 constrained 信号。"),
    ("removal constraint", "移除约束",
     "异步输入仍有效时发生的时钟边沿与随后撤销异步控制信号之间所需的最短时间。类似移除异步控制信号的 hold 检查。若异步输入在时钟边沿后过早变为无效，寄存器数据不确定，因为时钟数据可能有效并与异步控制冲突。"),
    ("RSPF", "RSPF",
     "Reduced Standard Parasitic Format，Cadence 定义的用于反标存储电路寄生信息的格式。"),
    ("scenario", "场景",
     "在 DMSA 分析中，分析设计的特定工作条件与模式组合。"),
    ("script", "脚本",
     r"含一系列 \texttt{pt\_shell} 命令的文本文件，可用 \cmd{source} 执行。"),
    ("SDF", "SDF",
     r"Standard Delay Format，存储电路信息用于反标的标准文件格式，包括延时（引脚到引脚单元延时与网延时）与时序检查（setup、hold、recovery、removal 等）。PrimeTime 用 \cmd{read\_sdf} 与 \cmd{write\_sdf} 读写 SDF。"),
    ("sensitize", "敏化",
     "找到或施加使特定路径在逻辑上激活并传播数据的输入向量。"),
    ("sequential logic", "时序逻辑",
     "含具有记忆或内部状态元件（如触发器、锁存器、寄存器或 RAM）的逻辑网络。"),
    ("session", "会话",
     r"一般指 PrimeTime 工具中当前运行的分析会话；也可指 \cmd{save\_session} 创建、\cmd{restore\_session} 读取的数据目录。"),
    ("setup constraint", "建立约束",
     "规定数据在锁入器件的时钟边沿之前必须在器件输入可用多长时间的时序约束。相对于时钟对时序路径施加最大延时。"),
    ("signal integrity", "信号完整性",
     "信号或网对串扰效应的免疫；网不受物理相邻网上转换或噪声影响的特性。"),
    ("signal pin", "信号引脚",
     "非 PG 引脚，如时钟、数据或复位引脚。"),
    ("skew", "偏斜",
     "时钟转换相对标称预期时间的偏移或变化量；或时钟网络中两点偏移量的差异。"),
    ("slack", "时序裕量（slack）",
     "避免违例的时间量。例如信号必须在不晚于 8~ns 到达单元输入而实际 5~ns 到达，则 slack 为 3~ns。slack 为 0 表示约束刚好满足；负 slack 表示时序违例。"),
    ("slew", "转换时间",
     "信号从低到高或从高到低变化所需时间；亦称 transition time。"),
    ("source latency", "源延迟",
     "时钟信号从理想波形原点到时钟定义点的传播时间。"),
    ("SPEF", "SPEF",
     "Standard Parasitic Exchange Format，OVI 定义的用于反标存储电路寄生信息的格式。"),
    ("SPICE", "SPICE",
     "Simulation program with integrated circuit emphasis；在晶体管、电容、电阻级分析电路操作的时基仿真工具。有多种来源的不同实现。"),
    ("startpoint", "起点",
     "时序路径在设计中开始的位置，即数据由时钟边沿发射或预期在特定时刻可用的位置。每个起点必须是寄存器时钟引脚或输入端口。"),
    ("static timing analysis", "静态时序分析",
     "通过考虑路径延时与时序约束，高效判断电路是否违反任何时序要求的分析。与门级仿真相比更快、更全面且不需测试向量，但不能替代仿真，因为不检查电路功能。"),
    ("static noise analysis", "静态噪声分析",
     "PrimeTime SI 执行的分析，确定最坏噪声效应以便最小化或消除。考虑物理相邻 aggressor 与受害网之间的交叉耦合电容及受害网的稳态（一或零）负载特性。"),
    ("synchronous", "同步",
     "两个时钟或信号之间的时序关系，特定转换同时发生或相位差随时间保持固定。"),
    ("task", "任务",
     "在 DMSA 与 HyperGrid 分布式分析中，管理进程为工作进程定义的自包含工作单元。"),
    ("Tcl", "Tcl",
     r"Tool command language；\texttt{pt\_shell} 接口所基于的标准命令脚本语言。"),
    ("Tcl procedure", "Tcl 过程",
     "见 procedure (Tcl)。"),
    ("threaded multicore analysis", "多线程多核分析",
     "使用多核提高性能的流程，对时序更新进行线程化并优化其他主要流程区域的处理。"),
    ("three-state", "三态",
     "器件输出（如总线驱动器）可处于三种逻辑状态之一：低（0）、高（1）或高阻（Z）。"),
    ("time borrowing", "时间借用",
     "见 borrowing（借用）。"),
    ("timing arc", "时序弧",
     "见 arc（弧）。"),
    ("timing exception", "时序例外",
     "PrimeTime 假定的默认（单周期）时序行为的例外。为正确分析电路，须指定每条不符合默认行为的路径。时序例外包括伪路径、多周期路径及需要与默认计算时间不同的最小或最大延时的路径。"),
    ("timing fanin and fanout", "时序扇入与扇出",
     "见 fanin 与 fanout。"),
    ("timing model", "时序模型",
     "含块时序特性但不一定含功能信息的电路模型。常用于层次化时序分析，因对整个超大芯片做单一 flat 分析可能过于耗时。"),
    ("transition time", "转换时间",
     "信号从低到高或从高到低变化所需时间。"),
    ("transitive fanin and fanout", "传递扇入与扇出",
     "见 fanin 与 fanout。"),
    ("transparent", "透明",
     "电平敏感锁存器门控输入被断言时的状态。此期间信号从输入传到输出，器件如同 buffer。"),
    ("true path", "真路径",
     "逻辑上可能工作的路径；可敏化并能传播数据的路径。"),
    ("uncertainty (clock uncertainty)", "不确定性（时钟不确定性）",
     "时钟边沿相对标称理想时钟时间的变化量。"),
    ("vector", "向量",
     "为测试或分析施加到器件输入的特定值集，或器件输出的结果值集；或用于敏化设计中路径进行分析的此类值序列。"),
    ("victim net", "受害网",
     "因与另一网（aggressor 网）之间的寄生交叉电容而产生不良串扰效应的网。"),
    ("voltage area", "电压区域",
     "芯片中使用与其他部分不同供电电压的物理区域。"),
    ("wire load model", "线负载模型",
     "布局前、无反标延时或寄生信息时用于时序分析的网电阻电容模型。PrimeTime 根据每条网的扇出与库指定参数估算线负载。"),
    ("worker process", "工作进程",
     "在 DMSA 与 HyperGrid 分布式分析中，执行分布式分析工作的一组进程之一，由管理进程控制。"),
]

lines = [
    r"% 术语表 Glossary",
    r"\bichapter{术语表}{Glossary}",
    r"\label{chap:glossary}",
    r"",
    r"\section{术语条目}",
    r"\subsection*{Glossary}",
    r"",
    r"以下条目按英文字母顺序排列。英文术语保留原文；定义已译为中文，命令名与技术标识符保持英文。",
    r"",
    r"\begin{description}[style=nextline, leftmargin=2.5cm, labelwidth=2.2cm, font=\normalfont]",
]

for en, zh, definition in ENTRIES:
    label = f"{zh}（\\textit{{{en}}}）" if zh != en else f"\\textit{{{en}}}"
    lines.append(f"  \\item[{label}] {definition}")

lines.extend([
    r"\end{description}",
    r"",
])

content = "\n".join(lines)
OUT.write_text(content, encoding="utf-8")
print(f"Wrote {OUT} ({len(content.encode('utf-8'))} bytes, {len(ENTRIES)} entries, {len(lines)} lines)")
